#!/bin/sh

OSES="linux"

set -e -o errexit

. make/include/colors.sh

if [ -z "${APP_VERSION}" ]; then
  . make/include/versioning.sh
fi

printf "${OK_COLOR}==> Building ${ERROR_COLOR}\n"

for OS in ${OSES}; do \
		 env GOOS=${OS} GOARCH=amd64 go build -o build/${OS}-amd64/groot-btrfs \
		 -ldflags="-X main.version=${APP_VERSION}" \
		 ./
done

printf "${NO_COLOR}"
