#!/bin/sh

set -o errexit

source scripts/prepare_test_btrfs

. make/include/colors.sh
printf "${OK_COLOR}==> Testing${NO_COLOR}\n"

# If no package is specified, run all the tests
# Specify a target like this:
# TEST_TARGET=driver make test
if [ -z "${TEST_TARGET}" ]; then
  gocov test $(go list ./... | grep -v /vendor/) -v -timeout 60m | gocov-xml > coverage.xml
else
  echo "Running tests for ${TEST_TARGET}"
  ginkgo $TEST_TARGET
  #gocov test $TEST_TARGET -v -timeout 60m
fi
